---
- name: setup ubuntu
  hosts: 127.0.0.1
  become: yes
  gather_facts: yes

  tasks:
    - name: install packages
      ansible.builtin.apt:
        name:
          - docker-compose
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == 'Debian'  # chek os